[workspace]
authors = ["ecamo19 <erickcamo19@gmail.com>"]
channels = ["conda-forge"]
name = "pysureau"
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[dependencies]
ruff = ">=0.12.9,<0.13"
nbdev = ">=3"
quarto = ">=1.7.33,<2"
python = ">=3.13"
jupyterlab = ">=4.4.6,<5"
fastcore = ">=1.8.7,<2"
shortuuid = ">=1.0.13,<2"
ipykernel = ">=7.1.0,<8"
pip = ">=25.2,<26"
numpy = ">=2.3.2,<3"
pandera = ">=0.26.0,<0.27"
pandas = ">=2.3.3,<3"
pydantic = ">=2.11.7,<3"
twine = ">=6.1.0,<7"
deno = ">=2.3.1,<2.4"
pixi-kernel = ">=0.7.1,<0.8"
setuptools = ">=82.0.0,<83"
wheel = ">=0.46.3,<0.47"
matplotlib = ">=3.10.8,<4"

[tasks]

[pypi-dependencies]
jupyterlab-quarto = ">=0.3.5, <0.4"
